name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neo'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, redis, pcntl
          coverage: none

      - name: Copy Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.github/.env.testing', '.env');"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer Dependencies
        run: composer install -n --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github
